"""
REST API for agent artifact storage.

Provides endpoints for listing and downloading artifacts generated by agents.
"""

from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from soloqueue.core.workspace import workspace

router = APIRouter(prefix="/api/agents", tags=["artifacts"])


def get_artifact_directory(agent_id: str) -> Optional[Path]:
    """
    Get the artifact directory path for an agent.

    Returns None if the directory doesn't exist.
    """
    artifact_dir = Path(".soloqueue") / "memory" / agent_id / "artifacts"
    try:
        resolved = workspace.resolve_path(str(artifact_dir))
        if resolved.exists() and resolved.is_dir():
            return resolved
    except Exception:
        pass
    return None


@router.get("/{agent_id}/artifacts")
async def list_artifacts(agent_id: str):
    """
    List artifacts for a specific agent.

    Returns list of artifact metadata (filename, path, size, modification time).
    """
    artifact_dir = get_artifact_directory(agent_id)
    if not artifact_dir:
        return {"artifacts": []}

    artifacts = []
    for file_path in artifact_dir.iterdir():
        if file_path.is_file():
            artifacts.append({
                "filename": file_path.name,
                "path": str(file_path.relative_to(workspace.root)),
                "size": file_path.stat().st_size,
                "modified": file_path.stat().st_mtime,
            })

    # Sort by modification time (newest first)
    artifacts.sort(key=lambda x: x["modified"], reverse=True)
    return {"artifacts": artifacts}


@router.get("/{agent_id}/artifacts/{filename}")
async def download_artifact(agent_id: str, filename: str):
    """
    Download a specific artifact file.

    Returns the file content with appropriate Content-Type header.
    """
    artifact_dir = get_artifact_directory(agent_id)
    if not artifact_dir:
        raise HTTPException(status_code=404, detail="Agent artifact directory not found")

    file_path = artifact_dir / filename
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="Artifact not found")

    # Basic security check: ensure file is within artifact directory
    try:
        file_path.relative_to(artifact_dir)
    except ValueError:
        raise HTTPException(status_code=403, detail="Access denied")

    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/octet-stream"
    )