package qqbot

import (
	"context"
	"errors"
	"strings"

	"github.com/xiaobaitu/soloqueue/internal/logger"
)

// ─── Constants ───────────────────────────────────────────────────────────────

const (
	// QQ message content limit (approximate). Split longer messages.
	qqMessageLimit = 2000

	// Busy reply when session is occupied.
	busyReply = "正在思考中，请稍后重试~"

	// Error prefix for agent errors.
	errorPrefix = "抱歉，处理消息时出错："
)

// ─── Session interface (decoupled from session package) ───────────────────────

// AskStreamResult contains the result of a streaming ask operation.
type AskStreamResult struct {
	Content          string   // final LLM response content
	ReasoningContent string   // thinking/reasoning content (if any)
	ImageURLs        []string // image URLs generated by ImageGenerate tool
}

// OnIntermediateFunc is called when intermediate assistant content becomes
// available during AskStream (e.g., content from an iteration that also
// produced tool calls). The implementation should send this content to the
// user as an intermediate message.
type OnIntermediateFunc func(ctx context.Context, content string)

// SessionProvider is the interface qqbot needs from the session layer.
// This decouples qqbot from the concrete session package, avoiding import cycles.
type SessionProvider interface {
	// AskStream performs a streaming ask and returns the final result.
	// It consumes the entire event stream internally.
	// onIntermediate is called for each intermediate assistant response
	// (content produced before a tool call). nil is acceptable.
	// Returns ErrSessionBusy if another ask is in progress.
	AskStream(ctx context.Context, prompt string, onIntermediate OnIntermediateFunc) (*AskStreamResult, error)

	// Clear clears the session context (conversation history).
	Clear(ctx context.Context) error
}

// ─── Errors ──────────────────────────────────────────────────────────────────

var ErrSessionBusy = errors.New("session: busy")

// ─── SessionBridge ───────────────────────────────────────────────────────────

// SessionBridge connects QQ messages to the SoloQueue Session.
// It receives QQ messages via the EventHandler interface, calls SessionProvider.AskStream,
// and sends the final reply back to QQ via the APIClient.
//
// Active messages (follow-up chunks, intermediate content, media) are routed
// through MessageQueue for rate limiting. Passive replies (ReplyMessage) are
// sent directly and are not rate-limited.
//
// Concurrency: the Session already serializes via inFlight (ErrSessionBusy).
// No additional guard is needed here — during async delegation the session
// correctly releases inFlight, allowing new messages to interleave.
type SessionBridge struct {
	sess    SessionProvider
	api     *APIClient
	log     *logger.Logger
	version string
	queue   *MessageQueue
}

// SessionBridgeOption configures a SessionBridge.
type SessionBridgeOption func(*SessionBridge)

// WithVersion sets the version string for /version slash command replies.
func WithVersion(v string) SessionBridgeOption {
	return func(b *SessionBridge) { b.version = v }
}

// WithMessageQueue sets the rate-limiting message queue for active messages.
// If set, sendActiveMessage, sendIntermediate, and sendMedia will push sends
// through the queue instead of sending immediately.
func WithMessageQueue(q *MessageQueue) SessionBridgeOption {
	return func(b *SessionBridge) { b.queue = q }
}

// NewSessionBridge creates a new SessionBridge.
func NewSessionBridge(sess SessionProvider, api *APIClient, log *logger.Logger, opts ...SessionBridgeOption) *SessionBridge {
	b := &SessionBridge{
		sess: sess,
		api:  api,
		log:  log,
	}
	for _, o := range opts {
		o(b)
	}
	return b
}

// OnQQMessage implements EventHandler. Called by the Gateway when a QQ message arrives.
func (b *SessionBridge) OnQQMessage(ctx context.Context, msg QQMessage) {
	b.log.InfoContext(ctx, logger.CatApp, "qqbot message received",
		"source", msg.Source,
		"content_len", len(msg.Content),
		"open_id", msg.OpenID)

	// Handle slash commands locally, consistent with TUI behavior.
	// Known builtins are handled here; unrecognized slash commands and skills
	// are forwarded to the LLM as normal input.
	if b.handleSlashCommand(ctx, msg) {
		return
	}

	// Use AskStream to capture the full response including reasoning content.
	// Pass onIntermediate to send intermediate assistant responses (content
	// from iterations that also produced tool calls) as active messages.
	result, err := b.sess.AskStream(ctx, msg.Content, func(ctx context.Context, content string) {
		b.sendIntermediate(ctx, msg, content)
	})
	if err != nil {
		if errors.Is(err, ErrSessionBusy) {
			b.sendReply(ctx, msg, MsgTypeText, busyReply)
			return
		}
		b.log.WarnContext(ctx, logger.CatApp, "qqbot ask stream failed",
			"err", err.Error())
		b.sendReply(ctx, msg, MsgTypeText, errorPrefix+err.Error())
		return
	}

	// Determine what to send:
	// - If content is non-empty, send content only (not reasoning/tool calls)
	// - If content is empty but reasoning is non-empty, send reasoning as fallback
	reply := result.Content
	if reply == "" && result.ReasoningContent != "" {
		reply = result.ReasoningContent
	}
	if reply == "" {
		b.sendReply(ctx, msg, MsgTypeText, "（思考完毕，无回复内容）")
		return
	}

	// Send generated images (if any) before the text reply.
	if len(result.ImageURLs) > 0 {
		b.sendImages(ctx, msg, result.ImageURLs)
	}

	b.log.InfoContext(ctx, logger.CatApp, "qqbot reply ready",
		"content_len", len(result.Content),
		"reasoning_len", len(result.ReasoningContent),
		"image_count", len(result.ImageURLs),
		"reply_len", len(reply))

	// Format as QQ-compatible markdown and send
	formatted := QQMarkdown(reply)
	b.sendReply(ctx, msg, MsgTypeMarkdown, formatted)
}

// ─── Slash Command Handling ──────────────────────────────────────────────────

// isSlashCommandInput checks if the message is a single-line slash command.
func isSlashCommandInput(input string) bool {
	trimmed := strings.TrimSpace(input)
	return !strings.Contains(trimmed, "\n") && strings.HasPrefix(trimmed, "/")
}

// handleSlashCommand processes slash commands locally, consistent with TUI behavior.
// Returns true if the command was handled (caller should not forward to LLM).
// Unrecognized slash commands return false so they are forwarded to LLM as normal input.
func (b *SessionBridge) handleSlashCommand(ctx context.Context, msg QQMessage) bool {
	content := strings.TrimSpace(msg.Content)
	if !isSlashCommandInput(content) {
		return false
	}

	name := strings.ToLower(content)

	switch name {
	case "/help", "/?":
		text := "Commands: /help /clear /version"
		b.sendReply(ctx, msg, MsgTypeText, text)
		return true

	case "/clear":
		if err := b.sess.Clear(ctx); err != nil {
			b.sendReply(ctx, msg, MsgTypeText, "clear session failed: "+err.Error())
		} else {
			b.sendReply(ctx, msg, MsgTypeText, "◆ context cleared")
		}
		return true

	case "/version":
		v := b.version
		if v == "" {
			v = "SoloQueue"
		} else {
			v = "SoloQueue " + v
		}
		b.sendReply(ctx, msg, MsgTypeText, v)
		return true

	case "/quit", "/exit", "/q":
		// QQ bot can't be quit via slash command; forward to LLM.
		return false

	default:
		// Unknown slash command: forward to LLM as normal input.
		return false
	}
}

// sendReply sends the reply text to QQ, splitting into chunks if it exceeds the limit.
// The first chunk is sent as a passive reply (with msg_id/msg_seq reference) so it
// appears threaded to the original message. Subsequent chunks are sent as active
// messages because QQ Bot API only allows one passive reply per incoming message.
func (b *SessionBridge) sendReply(ctx context.Context, msg QQMessage, msgType int, text string) {
	if len(text) <= qqMessageLimit {
		if err := b.api.ReplyMessage(ctx, msg, msgType, text); err != nil {
			b.log.WarnContext(ctx, logger.CatApp, "qqbot reply send failed",
				"err", err.Error())
		}
		return
	}

	// Use markdown-aware splitting for markdown, plain split for text
	var chunks []string
	if msgType == MsgTypeMarkdown {
		chunks = SplitMarkdown(text, qqMessageLimit)
	} else {
		chunks = splitMessage(text, qqMessageLimit)
	}

	// First chunk: passive reply (with msg_id/msg_seq)
	if err := b.api.ReplyMessage(ctx, msg, msgType, chunks[0]); err != nil {
		b.log.WarnContext(ctx, logger.CatApp, "qqbot first chunk reply failed",
			"err", err.Error())
		return
	}

	// Remaining chunks: active messages (no msg_id/msg_seq) — QQ only allows one passive reply
	for i := 1; i < len(chunks); i++ {
		if err := b.sendActiveMessage(ctx, msg, msgType, chunks[i]); err != nil {
			b.log.WarnContext(ctx, logger.CatApp, "qqbot follow-up chunk send failed",
				"chunk", i+1, "total", len(chunks), "err", err.Error())
			return
		}
	}
}

// sendActiveMessage sends an active message (no msg_id/msg_seq reference) to
// the same conversation as msg. If a MessageQueue is configured, the send is
// enqueued for rate-limited delivery (non-blocking, error silenced). Otherwise
// it is sent immediately.
func (b *SessionBridge) sendActiveMessage(ctx context.Context, msg QQMessage, msgType int, text string) error {
	if b.queue != nil {
		b.queue.Push(func() {
			_ = b.sendActiveMessageDirect(context.Background(), msg, msgType, text)
		})
		return nil
	}
	return b.sendActiveMessageDirect(ctx, msg, msgType, text)
}

// sendActiveMessageDirect sends the message immediately, bypassing the rate
// limiter queue. This is used internally by sendActiveMessage (for direct mode)
// and by the queue worker goroutine.
func (b *SessionBridge) sendActiveMessageDirect(ctx context.Context, msg QQMessage, msgType int, text string) error {
	var err error
	switch msg.Source {
	case SourceC2C:
		err = b.api.SendC2CMessage(ctx, msg.TargetOpenID, msgType, text, "", 0)
	case SourceGroup:
		err = b.api.SendGroupMessage(ctx, msg.TargetOpenID, msgType, text, "", 0)
	case SourceDirect:
		err = b.api.SendDirectMessage(ctx, msg.ChatID, msgType, text, "", 0)
	case SourcePublicGuild:
		err = b.api.SendDirectMessage(ctx, msg.ChatID, msgType, text, "", 0)
	}
	return err
}

// sendIntermediate sends an intermediate assistant message as an active message
// (no message reference), so it appears as a new message from the bot rather
// than a reply to the original user message. This allows multiple intermediate
// messages per incoming message.
func (b *SessionBridge) sendIntermediate(ctx context.Context, msg QQMessage, text string) {
	if err := b.sendActiveMessage(ctx, msg, MsgTypeText, text); err != nil {
		b.log.WarnContext(ctx, logger.CatApp, "qqbot intermediate send failed",
			"err", err.Error(),
		)
	}
}

// ─── Message Splitting ────────────────────────────────────────────────────────

// splitMessage splits text into chunks of at most maxLen bytes,
// preferring to split at newline boundaries.
func splitMessage(text string, maxLen int) []string {
	if len(text) <= maxLen {
		return []string{text}
	}

	var chunks []string
	for len(text) > maxLen {
		// Try to find a newline near the end of the chunk
		splitAt := maxLen
		idx := strings.LastIndex(text[:maxLen], "\n")
		if idx > maxLen/2 {
			splitAt = idx + 1
		}
		chunks = append(chunks, text[:splitAt])
		text = text[splitAt:]
	}
	if text != "" {
		chunks = append(chunks, text)
	}
	return chunks
}

// sendImages uploads each image URL to QQ and sends as rich media (active message, NOT reply).
// We use active messages here because QQ only delivers one被动 reply per incoming message.
func (b *SessionBridge) sendImages(ctx context.Context, msg QQMessage, urls []string) {
	targetType, targetID := imageUploadTarget(msg)
	if targetType == "" {
		b.log.WarnContext(ctx, logger.CatApp, "qqbot: unsupported source for image upload",
			"source", msg.Source)
		return
	}
	for i, url := range urls {
		fi, err := b.api.UploadFile(ctx, targetType, targetID, FileTypeImage, url)
		if err != nil {
			b.log.WarnContext(ctx, logger.CatApp, "qqbot: image upload failed",
				"url", url, "err", err.Error())
			continue
		}
		if err := b.sendMedia(ctx, msg, fi.FileInfo); err != nil {
			b.log.WarnContext(ctx, logger.CatApp, "qqbot: image send failed",
				"index", i+1, "err", err.Error())
		} else {
			b.log.InfoContext(ctx, logger.CatApp, "qqbot: image sent",
				"index", i+1)
		}
	}
}

// sendMedia sends a rich media message as an active message (no msg_id reference).
func (b *SessionBridge) sendMedia(ctx context.Context, msg QQMessage, fileInfo string) error {
	return b.sendActiveMessage(ctx, msg, MsgTypeMedia, fileInfo)
}

// imageUploadTarget returns the (targetType, targetID) pair for QQ rich media upload.
// targetType is "user" for C2C/Direct and "group" for Group, per QQ Bot API.
func imageUploadTarget(msg QQMessage) (targetType, targetID string) {
	switch msg.Source {
	case SourceC2C:
		return "user", msg.TargetOpenID
	case SourceGroup:
		return "group", msg.TargetOpenID
	case SourceDirect:
		return "user", msg.OpenID
	case SourcePublicGuild:
		return "user", msg.OpenID
	default:
		return "", ""
	}
}
